<?php

namespace Shop\ShippingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShippingMethodPriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShippingMethodPriceRepository extends EntityRepository
{
}
