weasty_ad:
    resource: "@WeastyAdBundle/Resources/config/routing.xml"
    prefix:   /

weasty_page:
    resource: "@WeastyPageBundle/Resources/config/routing.xml"
    prefix:   /

weasty_news:
    resource: "@WeastyNewsBundle/Resources/config/routing.xml"
    prefix:   /

shop_discount:
    resource: "@ShopDiscountBundle/Resources/config/routing.xml"
    prefix:   /

weasty_admin:
    resource: "@WeastyAdminBundle/Resources/config/routing.xml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /sonata_admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /sonata_admin

shop_admin:
    resource: "@ShopAdminBundle/Resources/config/routing.xml"
    prefix:   /

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

weasty_money:
    resource: "@WeastyMoneyBundle/Resources/config/routing.xml"
    prefix:   /

weasty_geonames:
    resource: "@WeastyGeonamesBundle/Resources/config/routing.xml"
    prefix:   /

weasty_resource:
    resource: "@WeastyResourceBundle/Resources/config/routing.xml"
    prefix:   /

shop_shipping:
    resource: "@ShopShippingBundle/Resources/config/routing.xml"
    prefix:   /

shop_order_management:
    resource: "@ShopOrderManagementBundle/Resources/config/routing.yml"
    prefix:   /

shop_user:
    resource: "@ShopUserBundle/Resources/config/routing.yml"
    prefix:   /

_shop_catalog:
    resource: "@ShopCatalogBundle/Resources/config/routing.yml"
    prefix:   /

shop_catalog:
    resource: "@ShopCatalogBundle/Resources/config/routing.xml"
    prefix:   /

shop_main:
    resource: "@ShopMainBundle/Resources/config/routing.xml"
    prefix:   /

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:   /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

shtumi_useful:
    resource: '@ShtumiUsefulBundle/Resources/config/routing.xml'