security:
    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
        Shop\UserBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_MANAGER:     ROLE_USER
        ROLE_ADMIN:       ROLE_MANAGER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_MANAGER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: 1qaz@WSX, roles: [ 'ROLE_ADMIN' ] }
        main:
            entity: { class: ShopUserBundle:User, property: username }

    firewalls:
        admin:
            pattern: /.*
            form_login:
                login_path: login
                check_path: login_check
                remember_me: true
            logout:
                path: logout
                target: /
            remember_me:
                key: MiPassphrase
                lifetime: 1800
                path: /.*
                domain: ~
            security: true
            anonymous: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/manager, roles: ROLE_MANAGER }
        - { path: ^/admin$, roles: ROLE_MANAGER }
        - { path: ^/admin/, roles: ROLE_ADMIN }