security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_MANAGER:       ROLE_USER
        ROLE_CATALOG_ADMIN: ROLE_USER
        ROLE_ADMIN:         [ROLE_MANAGER, ROLE_CATALOG_ADMIN]
        ROLE_SUPER_ADMIN:   [ROLE_USER, ROLE_MANAGER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            #id: fos_user.user_provider.username_email
            id: fos_user.user_manager

    firewalls:
        admin:
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/manager, roles: ROLE_MANAGER }
        - { path: ^/admin$, roles: [ROLE_CATALOG_ADMIN, ROLE_MANAGER, ROLE_ADMIN] }
        - { path: ^/adminCatalog/, roles: ROLE_CATALOG_ADMIN }
        - { path: ^/admin/, roles: ROLE_ADMIN }
    acl:
        connection: default