<?php

namespace Shop\CatalogBundle\Entity;

use Weasty\DoctrineBundle\Entity\AbstractRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends AbstractRepository
{

    /**
     * @param $formattedNames
     * @return array
     */
    public function findCategoriesByName($formattedNames){

        if(!$formattedNames){
            return array();
        }

        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
            ->select('c.*')
            ->from('ShopCatalogBundle:Category', 'c')
            ->andWhere($qb->expr()->in("REPLACE(LOWER(c.name), ' ', '')", $formattedNames))
        ;

        $rsm = $this->createResultSetMappingFromMetadata('ShopCatalogBundle:Category', 'c');

        $sql = (string)$this->convertDqlToSql($qb);
        $query = $this->getEntityManager()->createNativeQuery($sql, $rsm);

        return $query->getResult();

    }

}
