<?php

namespace Shop\CatalogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContractorCurrencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractorCurrencyRepository extends EntityRepository
{
}
