shop_catalog_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ShopCatalogBundle:Default:index }

parameters:
    pattern: /admin/parameters
    defaults: { _controller: ShopCatalogBundle:AdminParameter:parameters }

parameter:
    pattern: /admin/parameter/{id}
    defaults: { _controller: ShopCatalogBundle:AdminParameter:parameter, id: null }

delete_parameter:
    pattern: /admi/deleteParameter/{id}
    defaults: { _controller: ShopCatalogBundle:AdminParameter:deleteParameter }

parameter_option:
    pattern: /admin/parameterOption/{parameterId}/{id}
    defaults: { _controller: ShopCatalogBundle:AdminParameter:parameterOption, id: null }

delete_parameter_option:
    pattern: /admin/deleteParameterOption/{id}
    defaults: { _controller: ShopCatalogBundle:AdminParameter:deleteParameterOption }

update_parameter_options:
    pattern: /admin/updateParameterOptions/{parameterId}
    defaults: { _controller: ShopCatalogBundle:AdminParameter:updateParameterOptions}

categories:
    pattern: /admin/categories
    defaults: { _controller: ShopCatalogBundle:AdminCategory:categories }

category:
    pattern: /admin/category/{id}
    defaults: { _controller: ShopCatalogBundle:AdminCategory:category, id: null }

delete_category:
    pattern: /admin/deleteCategory/{id}
    defaults: { _controller: ShopCatalogBundle:AdminCategory:deleteCategory }

category_parameter:
    pattern: /admin/categoryParameter/{categoryId}/{id}
    defaults: { _controller: ShopCatalogBundle:AdminCategory:categoryParameter, id: null }

category_parameters:
    pattern: /admin/categoryParameters/{categoryId}
    defaults: { _controller: ShopCatalogBundle:AdminCategory:categoryParameters }

delete_category_parameter:
    pattern: /admin/deleteCategoryParameter/{id}
    defaults: { _controller: ShopCatalogBundle:AdminCategory:deleteCategoryParameter }

update_category_parameters:
    pattern: /admin/updateCategoryParameters/{categoryId}
    defaults: { _controller: ShopCatalogBundle:AdminCategory:updateCategoryParameters }
