shop_catalog_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ShopCatalogBundle:Default:index }

parameters:
    pattern: /admin/parameters
    defaults: { _controller: ShopCatalogBundle:AdminParameter:parameters }

parameter:
    pattern: /admin/parameter/{id}
    defaults: { _controller: ShopCatalogBundle:AdminParameter:parameter, id: null }

delete_parameter:
    pattern: /admi/deleteParameter/{id}
    defaults: { _controller: ShopCatalogBundle:AdminParameter:deleteParameter }

parameter_option:
    pattern: /admin/parameterOption/{parameterId}/{id}
    defaults: { _controller: ShopCatalogBundle:AdminParameter:parameterOption, id: null }

delete_parameter_option:
    pattern: /admin/deleteParameterOption/{id}
    defaults: { _controller: ShopCatalogBundle:AdminParameter:deleteParameterOption }

update_parameter_options:
    pattern: /admin/updateParameterOptions/{parameterId}
    defaults: { _controller: ShopCatalogBundle:AdminParameter:updateParameterOptions}

categories:
    pattern: /admin/categories
    defaults: { _controller: ShopCatalogBundle:AdminCategory:categories }

category:
    pattern: /admin/category/{id}
    defaults: { _controller: ShopCatalogBundle:AdminCategory:category, id: null }

delete_category:
    pattern: /admin/deleteCategory/{id}
    defaults: { _controller: ShopCatalogBundle:AdminCategory:deleteCategory }

category_parameters:
    pattern: /admin/categoryParameters/{categoryId}
    defaults: { _controller: ShopCatalogBundle:AdminCategory:categoryParameters }

category_parameter:
    pattern: /admin/categoryParameter/{categoryId}/{id}
    defaults: { _controller: ShopCatalogBundle:AdminCategory:categoryParameter, id: null }

delete_category_parameter:
    pattern: /admin/deleteCategoryParameter/{id}
    defaults: { _controller: ShopCatalogBundle:AdminCategory:deleteCategoryParameter }

update_category_parameters:
    pattern: /admin/updateCategoryParameters/{categoryId}
    defaults: { _controller: ShopCatalogBundle:AdminCategory:updateCategoryParameters }

proposals:
    pattern: /admin/proposals/{categoryId}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:proposals }

proposal:
    pattern: /admin/proposal/{categoryId}/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:proposal, id: null }

delete_proposal:
    pattern: /admin/deleteProposal/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:deleteProposal }

proposal_price:
    pattern: /admin/proposalPrice/{proposalId}/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:proposalPrice, id: null }

delete_proposal_price:
    pattern: /admin/deleteProposalPrice/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:deleteProposalPrice }

manufacturers:
    pattern: /admin/manufacturers
    defaults: { _controller: ShopCatalogBundle:AdminManufacturer:manufacturers }

manufacturer:
    pattern: /admin/manufacturer/{id}
    defaults: { _controller: ShopCatalogBundle:AdminManufacturer:manufacturer, id: null }

delete_manufacturer:
    pattern: /admin/deleteManufacturer/{id}
    defaults: { _controller: ShopCatalogBundle:AdminManufacturer:deleteManufacturer }

actions:
    pattern: /admin/actions
    defaults: { _controller: ShopCatalogBundle:AdminAction:actions }

update_actions_positions:
    pattern: /admin/actions/updatePositions
    defaults: { _controller: ShopCatalogBundle:AdminAction:updateActionsPosition }

action:
    pattern: /admin/action/{id}
    defaults: { _controller: ShopCatalogBundle:AdminAction:action, id: null }

delete_action:
    pattern: /admin/deleteAction/{id}
    defaults: { _controller: ShopCatalogBundle:AdminAction:deleteAction }
shop_cart:
    pattern: /shopCart
    defaults: { _controller: ShopCatalogBundle:ShopCart:default }
shop_cart_order:
    pattern: /shopCart/order
    defaults: { _controller: ShopCatalogBundle:ShopCart:order }

orders:
    pattern: /admin/orders
    defaults: { _controller: ShopCatalogBundle:AdminOrder:orders }

order:
    pattern: /admin/order/{id}
    defaults: { _controller: ShopCatalogBundle:AdminOrder:order }
