#@TODO continue converting to routins.xml
proposals:
    pattern: /adminCatalog/proposals/{categoryId}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:proposals }

proposals_browser:
    pattern: /adminCatalog/proposalsBrowser/{categoryId}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:proposalsBrowser, categoryId: null }

proposal:
    pattern: /adminCatalog/proposal/{categoryId}/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:proposal, id: null }

proposal_seo:
    pattern: /adminCatalog/proposalSeo/{categoryId}/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:proposal, _form_type: weasty_admin_seo_type }

delete_proposal:
    pattern: /adminCatalog/deleteProposal/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:deleteProposal }

popular_proposals:
    pattern: /adminCatalog/popularProposals
    defaults: { _controller: ShopCatalogBundle:AdminPopularProposal:proposals }

update_popular_proposals:
    pattern: /adminCatalog/updatePopularProposals
    defaults: { _controller: ShopCatalogBundle:AdminPopularProposal:updateProposals }

popular_proposal:
    pattern: /adminCatalog/popularProposal/{id}
    defaults: { _controller: ShopCatalogBundle:AdminPopularProposal:proposal, id: null }

delete_popular_proposal:
    pattern: /adminCatalog/deletePopularProposal/{id}
    defaults: { _controller: ShopCatalogBundle:AdminPopularProposal:deleteProposal }

proposal_price:
    pattern: /adminCatalog/proposalPrice/{proposalId}/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:proposalPrice, id: null }

proposal_prices:
    pattern: /adminCatalog/proposalPrices/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:proposalPrices }

delete_proposal_price:
    pattern: /adminCatalog/deleteProposalPrice/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:deleteProposalPrice }

proposal_image:
    pattern: /adminCatalog/proposalImages/{proposalId}/image/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:proposalImage, id: null }

proposal_set_main_image:
    pattern: /adminCatalog/proposalImages/{proposalId}/setMainImage/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:proposalSetMainImage }

proposal_images:
    pattern: /adminCatalog/proposalImages/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:proposalImages }

delete_proposal_image:
    pattern: /adminCatalog/proposalImages/{proposalId}/deleteImage/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:deleteProposalImage }

manufacturers:
    pattern: /adminCatalog/manufacturers
    defaults: { _controller: ShopCatalogBundle:AdminManufacturer:manufacturers }

manufacturer:
    pattern: /adminCatalog/manufacturer/{id}
    defaults: { _controller: ShopCatalogBundle:AdminManufacturer:manufacturer, id: null }

delete_manufacturer:
    pattern: /adminCatalog/deleteManufacturer/{id}
    defaults: { _controller: ShopCatalogBundle:AdminManufacturer:deleteManufacturer }

shop_cart:
    pattern: /shopCart
    defaults: { _controller: ShopCatalogBundle:ShopCart:default }
shop_cart_order:
    pattern: /shopCart/order
    defaults: { _controller: ShopCatalogBundle:ShopCart:order }

contractors:
    pattern: /admin/contractors
    defaults: { _controller: ShopCatalogBundle:AdminContractor:contractors }

contractor:
    pattern: /admin/contractor/{id}
    defaults: { _controller: ShopCatalogBundle:AdminContractor:contractor, id: null }

delete_contractor:
    pattern: /admin/deleteContractor/{id}
    defaults: { _controller: ShopCatalogBundle:AdminContractor:deleteContractor }

contractor_currency:
    pattern: /admin/contractor/{contractorId}/currency/{id}
    defaults: { _controller: ShopCatalogBundle:AdminContractor:contractorCurrency, id: null }

delete_contractor_currency:
    pattern: /admin/contractor/{contractorId}/deleteCurrency/{id}
    defaults: { _controller: ShopCatalogBundle:AdminContractor:deleteContractorCurrency }

price_lists:
    pattern: /adminCatalog/priceLists
    defaults: { _controller: ShopCatalogBundle:AdminPriceList:priceLists }

price_list:
    pattern: /adminCatalog/priceList/{id}
    defaults: { _controller: ShopCatalogBundle:AdminPriceList:priceList, id: null }

create_price_list:
    pattern: /adminCatalog/createPriceList
    defaults: { _controller: ShopCatalogBundle:AdminPriceList:createPriceList }

price_list_aliases:
    pattern: /adminCatalog/priceListAliases/{id}
    defaults: { _controller: ShopCatalogBundle:AdminPriceList:priceListsAliases }

download_price_list:
    pattern: /adminCatalog/downloadPriceList/{id}
    defaults: { _controller: ShopCatalogBundle:AdminPriceList:downloadPriceList }

parse_price_list:
    pattern: /adminCatalog/parsePriceList/{id}
    defaults: { _controller: ShopCatalogBundle:AdminPriceList:parsePriceList }

delete_price_list:
    pattern: /adminCatalog/deletePriceList/{id}
    defaults: { _controller: ShopCatalogBundle:AdminPriceList:deletePriceList }