shop_catalog_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ShopCatalogBundle:Default:index }

parameters:
    pattern: /adminCatalog/parameters
    defaults: { _controller: ShopCatalogBundle:AdminParameter:parameters }

parameter:
    pattern: /adminCatalog/parameter/{id}
    defaults: { _controller: ShopCatalogBundle:AdminParameter:parameter, id: null }

delete_parameter:
    pattern: /adminCatalog/deleteParameter/{id}
    defaults: { _controller: ShopCatalogBundle:AdminParameter:deleteParameter }

parameter_option:
    pattern: /adminCatalog/parameterOption/{parameterId}/{id}
    defaults: { _controller: ShopCatalogBundle:AdminParameter:parameterOption, id: null }

delete_parameter_option:
    pattern: /adminCatalog/deleteParameterOption/{id}
    defaults: { _controller: ShopCatalogBundle:AdminParameter:deleteParameterOption }

update_parameter_options:
    pattern: /adminCatalog/updateParameterOptions/{parameterId}
    defaults: { _controller: ShopCatalogBundle:AdminParameter:updateParameterOptions}

categories:
    pattern: /adminCatalog/categories
    defaults: { _controller: ShopCatalogBundle:AdminCategory:categories }

category:
    pattern: /adminCatalog/category/{id}
    defaults: { _controller: ShopCatalogBundle:AdminCategory:category, id: null }

delete_category:
    pattern: /adminCatalog/deleteCategory/{id}
    defaults: { _controller: ShopCatalogBundle:AdminCategory:deleteCategory }

category_parameters:
    pattern: /adminCatalog/categoryParameters/{categoryId}
    defaults: { _controller: ShopCatalogBundle:AdminCategory:categoryParameters }

category_parameter:
    pattern: /adminCatalog/categoryParameter/{categoryId}/{id}
    defaults: { _controller: ShopCatalogBundle:AdminCategory:categoryParameter, id: null }

delete_category_parameter:
    pattern: /adminCatalog/deleteCategoryParameter/{id}
    defaults: { _controller: ShopCatalogBundle:AdminCategory:deleteCategoryParameter }

update_category_parameters:
    pattern: /adminCatalog/updateCategoryParameters/{categoryId}
    defaults: { _controller: ShopCatalogBundle:AdminCategory:updateCategoryParameters }

proposals:
    pattern: /adminCatalog/proposals/{categoryId}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:proposals }

proposal:
    pattern: /adminCatalog/proposal/{categoryId}/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:proposal, id: null }

delete_proposal:
    pattern: /adminCatalog/deleteProposal/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:deleteProposal }

proposal_price:
    pattern: /adminCatalog/proposalPrice/{proposalId}/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:proposalPrice, id: null }

proposal_prices:
    pattern: /adminCatalog/proposalPrices/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:proposalPrices }

delete_proposal_price:
    pattern: /adminCatalog/deleteProposalPrice/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:deleteProposalPrice }

proposal_image:
    pattern: /adminCatalog/proposalImages/{proposalId}/image/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:proposalImage, id: null }

proposal_set_main_image:
    pattern: /adminCatalog/proposalImages/{proposalId}/setMainImage/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:proposalSetMainImage }

proposal_images:
    pattern: /adminCatalog/proposalImages/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:proposalImages }

delete_proposal_image:
    pattern: /adminCatalog/proposalImages/{proposalId}/deleteImage/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:deleteProposalImage }

manufacturers:
    pattern: /adminCatalog/manufacturers
    defaults: { _controller: ShopCatalogBundle:AdminManufacturer:manufacturers }

manufacturer:
    pattern: /adminCatalog/manufacturer/{id}
    defaults: { _controller: ShopCatalogBundle:AdminManufacturer:manufacturer, id: null }

delete_manufacturer:
    pattern: /adminCatalog/deleteManufacturer/{id}
    defaults: { _controller: ShopCatalogBundle:AdminManufacturer:deleteManufacturer }

actions:
    pattern: /admin/actions
    defaults: { _controller: ShopCatalogBundle:AdminAction:actions }

update_actions_positions:
    pattern: /admin/actions/updatePositions
    defaults: { _controller: ShopCatalogBundle:AdminAction:updateActionsPosition }

action:
    pattern: /admin/action/{id}
    defaults: { _controller: ShopCatalogBundle:AdminAction:action, id: null }

delete_action:
    pattern: /admin/deleteAction/{id}
    defaults: { _controller: ShopCatalogBundle:AdminAction:deleteAction }
shop_cart:
    pattern: /shopCart
    defaults: { _controller: ShopCatalogBundle:ShopCart:default }
shop_cart_order:
    pattern: /shopCart/order
    defaults: { _controller: ShopCatalogBundle:ShopCart:order }

contractors:
    pattern: /admin/contractors
    defaults: { _controller: ShopCatalogBundle:AdminContractor:contractors }

contractor:
    pattern: /admin/contractor/{id}
    defaults: { _controller: ShopCatalogBundle:AdminContractor:contractor, id: null }

delete_contractor:
    pattern: /admin/deleteContractor/{id}
    defaults: { _controller: ShopCatalogBundle:AdminContractor:deleteContractor }

contractor_currency:
    pattern: /admin/contractor/{contractorId}/currency/{id}
    defaults: { _controller: ShopCatalogBundle:AdminContractor:contractorCurrency, id: null }

delete_contractor_currency:
    pattern: /admin/contractor/{contractorId}/deleteCurrency/{id}
    defaults: { _controller: ShopCatalogBundle:AdminContractor:deleteContractorCurrency }

price_lists:
    pattern: /adminCatalog/priceLists
    defaults: { _controller: ShopCatalogBundle:AdminPriceList:priceLists }

price_list:
    pattern: /adminCatalog/priceList/{id}
    defaults: { _controller: ShopCatalogBundle:AdminPriceList:priceList, id: null }

create_price_list:
    pattern: /adminCatalog/createPriceList
    defaults: { _controller: ShopCatalogBundle:AdminPriceList:createPriceList }

price_list_aliases:
    pattern: /adminCatalog/priceListAliases/{id}
    defaults: { _controller: ShopCatalogBundle:AdminPriceList:priceListsAliases }

download_price_list:
    pattern: /adminCatalog/downloadPriceList/{id}
    defaults: { _controller: ShopCatalogBundle:AdminPriceList:downloadPriceList }

parse_price_list:
    pattern: /adminCatalog/parsePriceList/{id}
    defaults: { _controller: ShopCatalogBundle:AdminPriceList:parsePriceList }

delete_price_list:
    pattern: /adminCatalog/deletePriceList/{id}
    defaults: { _controller: ShopCatalogBundle:AdminPriceList:deletePriceList }

shipping_methods:
    pattern: /admin/shippingMethods
    defaults: { _controller: ShopCatalogBundle:AdminShippingMethod:shippingMethods }

shipping_method:
    pattern: /admin/shippingMethod/{id}
    defaults: { _controller: ShopCatalogBundle:AdminShippingMethod:shippingMethod, id: null }

delete_shipping_method:
    pattern: /admin/deleteShippingMethod/{id}
    defaults: { _controller: ShopCatalogBundle:AdminShippingMethod:deleteShippingMethod }
