#@TODO continue converting to routins.xml
proposals:
    pattern: /adminCatalog/proposals/{categoryId}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:proposals }
    options:
        title: shop.proposals
        parent: category
        resourceKey: category||proposal||price

proposals_browser:
    pattern: /adminCatalog/proposalsBrowser/{categoryId}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:proposalsBrowser, categoryId: null }

proposal:
    pattern: /adminCatalog/proposal/{categoryId}/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:proposal, id: null }
    options:
        title: %name%||shop.proposal.add
        parent: proposals
        resourceKey: proposal

proposal_seo:
    pattern: /adminCatalog/proposalSeo/{categoryId}/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:proposal, _form_type: weasty_admin_seo_type }
    options:
        title: shop.proposal.seo
        parent: proposal
        resourceKey: proposal

delete_proposal:
    pattern: /adminCatalog/deleteProposal/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:deleteProposal }

popular_proposals:
    pattern: /adminCatalog/popularProposals
    defaults: { _controller: ShopCatalogBundle:AdminPopularProposal:proposals }

update_popular_proposals:
    pattern: /adminCatalog/updatePopularProposals
    defaults: { _controller: ShopCatalogBundle:AdminPopularProposal:updateProposals }

popular_proposal:
    pattern: /adminCatalog/popularProposal/{id}
    defaults: { _controller: ShopCatalogBundle:AdminPopularProposal:proposal, id: null }

delete_popular_proposal:
    pattern: /adminCatalog/deletePopularProposal/{id}
    defaults: { _controller: ShopCatalogBundle:AdminPopularProposal:deleteProposal }

proposal_prices:
    pattern: /adminCatalog/proposalPrices/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:proposalPrices }
    options:
        title: shop.proposal.prices
        resourceKey: proposal
        parent: proposal

proposal_price:
    pattern: /adminCatalog/proposalPrice/{proposalId}/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:proposalPrice, id: null }
    options:
        title: shop.proposal.price
        resourceKey: proposalPrice
        parent: proposal_prices

delete_proposal_price:
    pattern: /adminCatalog/deleteProposalPrice/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:deleteProposalPrice }

proposal_images:
    pattern: /adminCatalog/proposalImages/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:proposalImages }
    options:
        title: shop.proposal.images
        resourceKey: proposal
        parent: proposal

proposal_image:
    pattern: /adminCatalog/proposalImages/{proposalId}/image/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:proposalImage, id: null }
    options:
        title: shop.proposal.image
        resourceKey: image
        parent: proposal_images

proposal_set_main_image:
    pattern: /adminCatalog/proposalImages/{proposalId}/setMainImage/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:proposalSetMainImage }

delete_proposal_image:
    pattern: /adminCatalog/proposalImages/{proposalId}/deleteImage/{id}
    defaults: { _controller: ShopCatalogBundle:AdminProposal:deleteProposalImage }

admin_catalog_manufacturers:
    pattern: /adminCatalog/manufacturers
    defaults: { _controller: ShopCatalogBundle:AdminManufacturer:manufacturers }
    options:
        title: shop.manufacturers
        parent: admin_catalog

admin_catalog_manufacturer:
    pattern: /adminCatalog/manufacturer/{id}
    defaults: { _controller: ShopCatalogBundle:AdminManufacturer:manufacturer, id: null }
    options:
        title: shop.manufacturer%name%
        resourceKey: manufacturer
        parent: admin_catalog_manufacturers

admin_catalog_manufacturer_delete:
    pattern: /adminCatalog/deleteManufacturer/{id}
    defaults: { _controller: ShopCatalogBundle:AdminManufacturer:deleteManufacturer }

contractors:
    pattern: /admin/contractors
    defaults: { _controller: ShopCatalogBundle:AdminContractor:contractors }

contractor:
    pattern: /admin/contractor/{id}
    defaults: { _controller: ShopCatalogBundle:AdminContractor:contractor, id: null }

delete_contractor:
    pattern: /admin/deleteContractor/{id}
    defaults: { _controller: ShopCatalogBundle:AdminContractor:deleteContractor }

contractor_currency:
    pattern: /admin/contractor/{contractorId}/currency/{id}
    defaults: { _controller: ShopCatalogBundle:AdminContractor:contractorCurrency, id: null }

delete_contractor_currency:
    pattern: /admin/contractor/{contractorId}/deleteCurrency/{id}
    defaults: { _controller: ShopCatalogBundle:AdminContractor:deleteContractorCurrency }

admin_catalog_price_lists:
    pattern: /adminCatalog/priceLists
    defaults: { _controller: ShopCatalogBundle:AdminPriceList:priceLists }
    options:
        title: shop.price_lists
        parent: admin_catalog

admin_catalog_price_list:
    pattern: /adminCatalog/priceList/{id}
    defaults: { _controller: ShopCatalogBundle:AdminPriceList:priceList, id: null }
    options:
        title: %name%||shop.price_list.add
        resourceKey: priceList
        parent: admin_catalog_price_lists

admin_catalog_price_list_create:
    pattern: /adminCatalog/createPriceList
    defaults: { _controller: ShopCatalogBundle:AdminPriceList:createPriceList }
    options:
        title: shop.price_list.create
        resourceKey: priceList
        parent: admin_catalog_price_lists

admin_catalog_price_list_aliases:
    pattern: /adminCatalog/priceListAliases/{id}
    defaults: { _controller: ShopCatalogBundle:AdminPriceList:priceListAliases }
    options:
        title: shop.price_list.settings%name%
        resourceKey: priceList
        parent: admin_catalog_price_list

admin_catalog_price_list_download:
    pattern: /adminCatalog/downloadPriceList/{id}
    defaults: { _controller: ShopCatalogBundle:AdminPriceList:downloadPriceList }

admin_catalog_price_list_parse:
    pattern: /adminCatalog/parsePriceList/{id}
    defaults: { _controller: ShopCatalogBundle:AdminPriceList:parsePriceList }

admin_catalog_price_list_delete:
    pattern: /adminCatalog/deletePriceList/{id}
    defaults: { _controller: ShopCatalogBundle:AdminPriceList:deletePriceList }