parameters:
#    shop_catalog.example.class: Shop\CatalogBundle\Example

services:
#    shop_catalog.example:
#        class: %shop_catalog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
